apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: venkatasudhakar33/demo-app:1.0
      ports:
        - containerPort: 8080
